spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csgo_spy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 20020213
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.youngfog.back_csgo_spy.domain